services:
  - docker

language: go

git:
  submodules: true
  quiet: true

jobs:
  include:
    - stage: Pre-build
      if: fork = false # We can only use encrypted ENV vars from trusted source (non-forks)
      name: Bake dockerized tooling
      script:
        - echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - hack/exec/travis-tooling-bootstrap.sh
    - stage: Build, test and bake
      name: Documentation generation
      script:
        - hack/exec/docs-generate.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN_DOCS
        local_dir: docs/public
        repo: trisacrypto/trisacrypto.github.io
        target_branch: master
        keep_history: false
        committer_from_gh: true
        on:
          branch: master
    - name: Build and testing
      script:
        - hack/exec/travis-build-bootstrap.sh
    - name: Build and publish PR image
      if: fork = false AND type = pull_request
      script:
        - echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - hack/exec/travis-publish-bootstrap.sh
    - name: Build and publish latest image
      if: fork = false AND type = push AND branch = master
      script:
        - echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - hack/exec/travis-publish-bootstrap.sh

notifications:
  email: false

branches:
  only:
    - master
