apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: trisa
build:
  artifacts:
    - image: trisacrypto/trisa
      bazel:
        target: //cmd/trisa:docker.tar
        args:
          - --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64
  tagPolicy:
    gitCommit: {}
  local:
    push: false
deploy: {}
profiles:
  - name: latest
    build:
      tagPolicy:
        sha256: {}
      local:
        push: true
  - name: dev
    build:
      tagPolicy:
        gitCommit: {}
      local:
        push: true
  - name: kind
    build:
      tagPolicy:
        gitCommit: {}
      local:
        push: true
    deploy:
      kustomize:
        path: hack/etc/k8s/vasps
