apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - vasp1-deployment.yaml
  - vasp1-service.yaml
  - vasp2-deployment.yaml
  - vasp2-service.yaml
  - vasp3-deployment.yaml
  - vasp3-service.yaml

secretGenerator:

  - name: vasp1
    files:
      - vasp1/config.yaml
      - vasp1/server.crt
      - vasp1/server.key
      - vasp1/trust.chain
  - name: vasp2
    files:
      - vasp2/config.yaml
      - vasp2/server.crt
      - vasp2/server.key
      - vasp2/trust.chain
  - name: vasp3
    files:
      - vasp3/config.yaml
      - vasp3/server.crt
      - vasp3/server.key
      - vasp3/trust.chain