apiVersion: apps/v1
kind: Deployment
metadata:
  name: vasp1
  labels:
    app: trisa
    entity: vasp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trisa
      entity: vasp1
  template:
    metadata:
      labels:
        app: trisa
        entity: vasp1
    spec:
      containers:
      - name: vasp
        image: trisacrypto/trisa
        imagePullPolicy: Never
        workingDir: /etc/trisa
        args: ["server"]
        ports:
        - name: grpc
          containerPort: 8091
        - name: admin
          containerPort: 8591
        volumeMounts:
        - name: config
          mountPath: /etc/trisa
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: grpc
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
        - name: config
          secret:
            secretName: vasp1

