#!/usr/bin/env python3

import json

CODE_FILE = "gleif.gen.go"
AUTHORITIES = "testdata/registrationAuthorities.json"
HEADERS = [
    "// Code generated by generate.py. DO NOT EDIT.",
    "// source: registrationAuthorities.json",
    "",
    "package gleif",
    "",
    "var registrationAuthorities = RegistrationAuthorities{",
    ""
]


def load_authorities(path=AUTHORITIES):
    with open(path, 'r') as f:
        return json.load(f)


def main():
    authorities = load_authorities()
    with open(CODE_FILE, 'w') as f:
        f.write("\n".join(HEADERS))

        for authority in authorities:
            f.write("\t{\n")
            f.write(f"\t\tOption: \"{authority.get('option')}\",\n")
            f.write(f"\t\tCountryName: \"{authority.get('country_name')}\",\n")
            f.write(f"\t\tCountry: \"{authority.get('country')}\",\n")
            f.write(f"\t\tJurisdiction: \"{authority.get('jurisdiction')}\",\n") # noqa
            f.write(f"\t\tRegister: \"{authority.get('register')}\",\n")
            f.write(f"\t\tOrganization: \"{authority.get('organization')}\",\n") # noqa
            f.write(f"\t\tWebsite: \"{authority.get('website')}\",\n")
            f.write(f"\t\tComments: `{authority.get('comments')}`,\n")
            f.write("\t},\n")

        f.write("}\n")


if __name__ == "__main__":
    main()
