package openvasp

import (
	"github.com/trisacrypto/trisa/pkg/ivms101"
	"github.com/trisacrypto/trisa/pkg/openvasp/trp/v3"
	"github.com/trisacrypto/trisa/pkg/slip0044"
	api "github.com/trisacrypto/trisa/pkg/trisa/api/v1beta1"
	generic "github.com/trisacrypto/trisa/pkg/trisa/data/generic/v1beta1"
	"github.com/trisacrypto/trisa/pkg/trisa/envelope"
	"google.golang.org/protobuf/encoding/protojson"
)

// OpenVASP Application Headers
const (
	APIVersionHeader        = "api-version"
	APIExtensionsHeader     = "api-extensions"
	RequestIdentifierHeader = "request-identifier"
	ContentTypeHeader       = "content-type"
)

// OpenVASP Application Header Values
const (
	APIVersion       = "3.1.0"
	ContentTypeValue = "application/json; charset=utf-8"
	ContentMediaType = "application/json"
	ContentPlainText = "text/plain"
)

// TRISA extensions
const (
	SealedTRISAExtension   = "sealed-trisa-envelope"
	UnsealedTRISAExtension = "unsealed-trisa-envelope"
)

// The TransactionPayload extension is used to provide information about the
// transaction on the blockchain or network so it can be linked to the identity
// information in the TRP payload.
type TransactionPayload struct {
	// Transaction ID on the blockchain or network.
	TxID string `json:"txid,omitempty"`

	// Crypto address of the originator and beneficiary.
	Originator  string `json:"originator,omitempty"`
	Beneficiary string `json:"beneficiary,omitempty"`

	// Amount and asset type of the transaction.
	Amount    float64 `json:"amount,omitempty"`
	AssetType string  `json:"asset_type,omitempty"`

	// The blockchain or network of the transaction.
	Network string `json:"network,omitempty"`

	// The RFC3339 timestamp of the transaction.
	Timestamp string `json:"timestamp,omitempty"`

	// Tags and extra JSON data about the transaction.
	Tag       string                 `json:"tag,omitempty"`
	ExtraJSON map[string]interface{} `json:"extra_json,omitempty"`
}

// The SealedTRISAEnvelope extension is used to faciliate the TRISA protocol by providing a
// JSON serialized version of the secure envelope that contains the transaction.
type SealedTRISAEnvelope struct {
	Envelope string `json:"envelope"`
}

// The UnsealedTRISAEnvelope extension is used to provide an unsealed version of a
// secure envelope where the key is unencrypted, allowing any party to decrypt the
// payload and access the identity and transaction information.
type UnsealedTRISAEnvelope struct {
	// Transaction ID generated by the originator.
	Id string `json:"id"`

	// The encrypted payload containing the IVMS101 identity and generic transaction.
	Payload []byte `json:"payload"`

	// Encryption key used to encrypt the payload, in this struct the key is unencrypted.
	EncryptionKey       []byte `json:"encryption_key"`
	EncryptionAlgorithm string `json:"encryption_algorithm"`

	// HMAC of the payload to ensure integrity.
	HMAC          []byte `json:"hmac"`
	HMACSecret    []byte `json:"hmac_secret"`
	HMACAlgorithm string `json:"hmac_algorithm"`
}

// Convert a TRISA envelope to a TRP payload. If the envelope is sealed, then this
// returns a payload with the SealedTRISAEnvelope extension. If the envelope is
// unsealed, then this returns a payload with the UnsealedTRISAEnvelope extension.
// If the envelope is in the clear then this returns a standard TRP payload with no
// TRISA extensions.
func EnvelopeToPayload(env *envelope.Envelope) (*trp.Inquiry, error) {
	if env == nil {
		return nil, trp.ErrNilEnvelope
	}

	var err error
	switch env.State() {
	case envelope.Sealed:
		// If sealed, just serialize the envelope to JSON.
		var envBytes []byte
		if envBytes, err = protojson.Marshal(env.Proto()); err != nil {
			return nil, err
		}
		return &trp.Inquiry{
			Extensions: map[string]interface{}{
				SealedTRISAExtension: &SealedTRISAEnvelope{
					Envelope: string(envBytes),
				},
			},
		}, nil
	case envelope.Unsealed:
		// If already unsealed, just return the wrapped envelope.
		proto := env.Proto()
		return &trp.Inquiry{
			Extensions: map[string]interface{}{
				UnsealedTRISAExtension: &UnsealedTRISAEnvelope{
					Id:                  proto.Id,
					Payload:             proto.Payload,
					EncryptionKey:       proto.EncryptionKey,
					EncryptionAlgorithm: proto.EncryptionAlgorithm,
					HMAC:                proto.Hmac,
					HMACSecret:          proto.HmacSecret,
					HMACAlgorithm:       proto.HmacAlgorithm,
				},
			},
		}, nil
	case envelope.Clear:
		// If in the clear, return a standard TRP payload.
		var payload *api.Payload
		if payload, err = env.Payload(); err != nil {
			return nil, err
		}

		// Parse the amount and asset type from the transaction.
		transaction := &generic.Transaction{}
		if err = payload.Transaction.UnmarshalTo(transaction); err != nil {
			return nil, err
		}

		inq := &trp.Inquiry{
			Asset:   &trp.Asset{},
			Amount:  transaction.Amount,
			IVMS101: &ivms101.IdentityPayload{},
		}
		if inq.Asset.SLIP044, err = slip0044.ParseCoinType(transaction.AssetType); err != nil {
			return nil, err
		}

		// Unmarshal the identity into the TRP payload.
		if err = payload.Identity.UnmarshalTo(inq.IVMS101); err != nil {
			return nil, err
		}
		return inq, nil
	case envelope.Unknown:
		return nil, trp.ErrUnknownState
	case envelope.Corrupted:
		return nil, trp.ErrInvalidState
	default:
		return nil, trp.ErrEnvelopeError
	}
}
