// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: trisa/api/v1beta1/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferState int32

const (
	TransferState_UNSPECIFIED TransferState = 0 // the transfer state is unknown or not specified
	TransferState_STARTED     TransferState = 1 // this is the first message in the TRISA workflow
	TransferState_PENDING     TransferState = 2 // action is required by the sending party
	TransferState_REVIEW      TransferState = 3 // action is required by the recieving party (rarely used)
	TransferState_REPAIR      TransferState = 4 // some state of the travel rule exchange requires repair
	TransferState_ACCEPTED    TransferState = 5 // the travel rule exchange is accepted and waiting the transaction
	TransferState_COMPLETED   TransferState = 6 // the travel rule and on-chain transaction have been completed
	TransferState_REJECTED    TransferState = 7 // the travel rule exchange is rejected and should not proceed
)

// Enum value maps for TransferState.
var (
	TransferState_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "STARTED",
		2: "PENDING",
		3: "REVIEW",
		4: "REPAIR",
		5: "ACCEPTED",
		6: "COMPLETED",
		7: "REJECTED",
	}
	TransferState_value = map[string]int32{
		"UNSPECIFIED": 0,
		"STARTED":     1,
		"PENDING":     2,
		"REVIEW":      3,
		"REPAIR":      4,
		"ACCEPTED":    5,
		"COMPLETED":   6,
		"REJECTED":    7,
	}
)

func (x TransferState) Enum() *TransferState {
	p := new(TransferState)
	*p = x
	return p
}

func (x TransferState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferState) Descriptor() protoreflect.EnumDescriptor {
	return file_trisa_api_v1beta1_api_proto_enumTypes[0].Descriptor()
}

func (TransferState) Type() protoreflect.EnumType {
	return &file_trisa_api_v1beta1_api_proto_enumTypes[0]
}

func (x TransferState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferState.Descriptor instead.
func (TransferState) EnumDescriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{0}
}

type ConfirmationType int32

const (
	ConfirmationType_UNKNOWN  ConfirmationType = 0
	ConfirmationType_SIMPLE   ConfirmationType = 1
	ConfirmationType_KEYTOKEN ConfirmationType = 2
	ConfirmationType_ONCHAIN  ConfirmationType = 3
)

// Enum value maps for ConfirmationType.
var (
	ConfirmationType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SIMPLE",
		2: "KEYTOKEN",
		3: "ONCHAIN",
	}
	ConfirmationType_value = map[string]int32{
		"UNKNOWN":  0,
		"SIMPLE":   1,
		"KEYTOKEN": 2,
		"ONCHAIN":  3,
	}
)

func (x ConfirmationType) Enum() *ConfirmationType {
	p := new(ConfirmationType)
	*p = x
	return p
}

func (x ConfirmationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmationType) Descriptor() protoreflect.EnumDescriptor {
	return file_trisa_api_v1beta1_api_proto_enumTypes[1].Descriptor()
}

func (ConfirmationType) Type() protoreflect.EnumType {
	return &file_trisa_api_v1beta1_api_proto_enumTypes[1]
}

func (x ConfirmationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmationType.Descriptor instead.
func (ConfirmationType) EnumDescriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{1}
}

type ServiceState_Status int32

const (
	ServiceState_UNKNOWN     ServiceState_Status = 0
	ServiceState_HEALTHY     ServiceState_Status = 1
	ServiceState_UNHEALTHY   ServiceState_Status = 2
	ServiceState_DANGER      ServiceState_Status = 3
	ServiceState_OFFLINE     ServiceState_Status = 4
	ServiceState_MAINTENANCE ServiceState_Status = 5
)

// Enum value maps for ServiceState_Status.
var (
	ServiceState_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "DANGER",
		4: "OFFLINE",
		5: "MAINTENANCE",
	}
	ServiceState_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"HEALTHY":     1,
		"UNHEALTHY":   2,
		"DANGER":      3,
		"OFFLINE":     4,
		"MAINTENANCE": 5,
	}
)

func (x ServiceState_Status) Enum() *ServiceState_Status {
	p := new(ServiceState_Status)
	*p = x
	return p
}

func (x ServiceState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_trisa_api_v1beta1_api_proto_enumTypes[2].Descriptor()
}

func (ServiceState_Status) Type() protoreflect.EnumType {
	return &file_trisa_api_v1beta1_api_proto_enumTypes[2]
}

func (x ServiceState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceState_Status.Descriptor instead.
func (ServiceState_Status) EnumDescriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{10, 0}
}

// Encrypted transaction envelope that is the outer layer of the TRISA information
// exchange protocol and facilitates the secure storage of KYC data in a transaction.
// The envelope specifies a unique id to reference the transaction out-of-band (e.g in
// the blockchain layer) and provides the necessary information so that only the
// originator and the beneficiary can decrypt the trnasaction data.
type SecureEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The transaction identifier generated by the sender. Any message concerning the
	// same blockhain transaction requires the same envelope ID on both sending and
	// responding RPCs.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Encrypted payload that contains the IVMS 101 IdentityPayload for compliance and
	// a generic transaction payload that is used to identify the transaction on the
	// blockchain or perform flow control messages in TRISA itself. This payload should
	// be encrypted using the encryption algorithm and key defined below.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Encryption key used to encrypt the compliance payload, usually generated on a
	// per-envelope basis. To seal the envelope, this key should be encrypted with the
	// public key of the recipient. If this key is in the clear, the sealed flag should
	// be false.
	EncryptionKey []byte `protobuf:"bytes,3,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	// The encryption algorithm used to encrypt the compliance payload. This string
	// should provide enough information for the recipient to understand how to decrypt
	// the payload including algorithm, variants, block length, etc.
	EncryptionAlgorithm string `protobuf:"bytes,4,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryption_algorithm,omitempty"`
	// HMAC signature calculated from encrypted encrypted compliance payload using the
	// hmac algorithm and secret defined below. This signature provides non-repudiation
	// to regulators and counterparties that ensure the envelope has not been tampered
	// with after receipt, particularly when comparing two envelopes.
	Hmac []byte `protobuf:"bytes,5,opt,name=hmac,proto3" json:"hmac,omitempty"`
	// The HMAC secret used to calculate the HMAC signature. To seal the envelope, this
	// secret should be encrypted with the public key of the recipient. If this secret
	// is in the clear, the sealed flag should be false.
	HmacSecret []byte `protobuf:"bytes,6,opt,name=hmac_secret,json=hmacSecret,proto3" json:"hmac_secret,omitempty"`
	// The algorithm used to calculate the HMAC signature. This string should provide
	// enough information for the recipient to understand how to compute the HMAC
	// including algorithm, block length, hashing function, etc.
	HmacAlgorithm string `protobuf:"bytes,7,opt,name=hmac_algorithm,json=hmacAlgorithm,proto3" json:"hmac_algorithm,omitempty"`
	// Rejection/TRISA errors should be specified in the SecureEnvelope for correct
	// compliance processing and not returned as a gRPC error. E.g. if the counterparty
	// wishes to send a TRISA error, they should send an OK gRPC response with the error
	// in this field. Networking errors such as unavailable, mTLS failure, or timeouts
	// are handled separately from compliance-related errors.
	Error *Error `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	// The RFC-3339 formatted timestamp at nanosecond resolution. Used to order
	// SecureEnvelopes related to the same transaction. While this timestamp is likely
	// the same as the sent_at timestamp in the compliance payload, it does not serve
	// the same purpose. The compliance payload timestamps are for non-repudiation,
	// whereas this timestamp is for envelope and communication management.
	Timestamp string `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Metadata related to the public key cryptography that seal the envelope by
	// encrypting the encryption key and hmac secret such that only the recipient can
	// fully decrypt the envelope. If the envelope is sealed, it indicates that the
	// encryption key and hmac secret are encrypted with a public key, whose signature
	// can be used for the recipient to identify the key pair required for decryption.
	Sealed             bool   `protobuf:"varint,11,opt,name=sealed,proto3" json:"sealed,omitempty"`
	PublicKeySignature string `protobuf:"bytes,12,opt,name=public_key_signature,json=publicKeySignature,proto3" json:"public_key_signature,omitempty"`
	// The state refers to the condition that the sending party feels that the secure
	// envelope exchange is in. This can optionally be used to signal to the
	// counterparty the intent of a transfer message
	TransferState TransferState `protobuf:"varint,13,opt,name=transfer_state,json=transferState,proto3,enum=trisa.api.v1beta1.TransferState" json:"transfer_state,omitempty"`
}

func (x *SecureEnvelope) Reset() {
	*x = SecureEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecureEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureEnvelope) ProtoMessage() {}

func (x *SecureEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureEnvelope.ProtoReflect.Descriptor instead.
func (*SecureEnvelope) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{0}
}

func (x *SecureEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecureEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SecureEnvelope) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *SecureEnvelope) GetEncryptionAlgorithm() string {
	if x != nil {
		return x.EncryptionAlgorithm
	}
	return ""
}

func (x *SecureEnvelope) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

func (x *SecureEnvelope) GetHmacSecret() []byte {
	if x != nil {
		return x.HmacSecret
	}
	return nil
}

func (x *SecureEnvelope) GetHmacAlgorithm() string {
	if x != nil {
		return x.HmacAlgorithm
	}
	return ""
}

func (x *SecureEnvelope) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SecureEnvelope) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SecureEnvelope) GetSealed() bool {
	if x != nil {
		return x.Sealed
	}
	return false
}

func (x *SecureEnvelope) GetPublicKeySignature() string {
	if x != nil {
		return x.PublicKeySignature
	}
	return ""
}

func (x *SecureEnvelope) GetTransferState() TransferState {
	if x != nil {
		return x.TransferState
	}
	return TransferState_UNSPECIFIED
}

// Payload contains the compliance identity information that must be exchanged in a
// secure fashion, transaction information for both counterparties to uniquely identify
// the transaction on the chain, and timestamps that are used for regulatory
// non-repudiation. This payload is serialized and encrypted to be sent in the
// SecureEnvelope as well as digitally signed to ensure that the payload has not been
// tampered with after transmission. The internal message types of the payload are
// purposefully generic to allow flexibility with the data needs for different exchanges.
type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identity contains any valid identity structure. The expected format is the
	// IVMS101 IdentityPayload which contains the originator and beneficiary identities,
	// the originator and beneficiary VASP identities, as well as the transfer path of
	// any intermediate VASPs. The identity payload can be bidirectional (containing
	// both originator and beneficiary identities) or unidirectional - containing only
	// the identity of the sender. In the bidirectional case, the identity may be
	// purposefully partial to allow the recipient to fill in the details. In the
	// unidirectional case, the identities must be collated after.
	Identity *anypb.Any `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Transaction contains network specific information about the exchange or transfer.
	// It can also contain transfer control messages such as Pending messages to
	// facilitate multi-message compliance exchanges. These messages must all be
	// digtially signed for auditing purposes.
	Transaction *anypb.Any `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// Timestamps that describe when the payload was originally sent and when it was
	// accepted or received by the counterparty. These timestamps must be in the payload
	// so that they are digitally signed for non-repudiation. Both timestamps should be
	// RFC-3339 formatted strings with timezone information.
	SentAt     string `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ReceivedAt string `protobuf:"bytes,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetIdentity() *anypb.Any {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Payload) GetTransaction() *anypb.Any {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *Payload) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *Payload) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

// Address specifies a crypto address that requires a proof-of-control verification.
// There are three types of verification: simple, key-based, and on-chain. In simple
// address confirmation, the counterparty simply replies y/n if they control the
// address. In key-based control, a token encrypted with the public keys is sent to the
// counterparty which must decrypt it with the private key and return it. In on-chain
// proof-of-control, a transaction is placed on the chain for some small random amount
// of the specified asset, random enough that it can be confirmed by the originator.
type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required fields for all address confirmation RPCs that identify the crypto
	// address and network that needs to be validated as well as the requested type.
	Confirmation  ConfirmationType `protobuf:"varint,1,opt,name=confirmation,proto3,enum=trisa.api.v1beta1.ConfirmationType" json:"confirmation,omitempty"`
	CryptoAddress string           `protobuf:"bytes,2,opt,name=crypto_address,json=cryptoAddress,proto3" json:"crypto_address,omitempty"`
	Network       string           `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	// Optional details that may be necessary for the specific chain such as the asset
	// type for chains that support multiple assets or a memo/destination tag.
	AssetType string `protobuf:"bytes,4,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	Tag       string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	// If the confirmation type is key/token or on-chain then additional details must
	// be specified for the address confirmation. If the confirmation type is simple,
	// then this field may be left empty.
	//
	// Types that are assignable to ConfirmationDetails:
	//
	//	*Address_KeyToken
	//	*Address_OnChain
	ConfirmationDetails isAddress_ConfirmationDetails `protobuf_oneof:"confirmation_details"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetConfirmation() ConfirmationType {
	if x != nil {
		return x.Confirmation
	}
	return ConfirmationType_UNKNOWN
}

func (x *Address) GetCryptoAddress() string {
	if x != nil {
		return x.CryptoAddress
	}
	return ""
}

func (x *Address) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Address) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *Address) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (m *Address) GetConfirmationDetails() isAddress_ConfirmationDetails {
	if m != nil {
		return m.ConfirmationDetails
	}
	return nil
}

func (x *Address) GetKeyToken() *KeyTokenQuery {
	if x, ok := x.GetConfirmationDetails().(*Address_KeyToken); ok {
		return x.KeyToken
	}
	return nil
}

func (x *Address) GetOnChain() *OnChainQuery {
	if x, ok := x.GetConfirmationDetails().(*Address_OnChain); ok {
		return x.OnChain
	}
	return nil
}

type isAddress_ConfirmationDetails interface {
	isAddress_ConfirmationDetails()
}

type Address_KeyToken struct {
	KeyToken *KeyTokenQuery `protobuf:"bytes,8,opt,name=key_token,json=keyToken,proto3,oneof"`
}

type Address_OnChain struct {
	OnChain *OnChainQuery `protobuf:"bytes,9,opt,name=on_chain,json=onChain,proto3,oneof"`
}

func (*Address_KeyToken) isAddress_ConfirmationDetails() {}

func (*Address_OnChain) isAddress_ConfirmationDetails() {}

// AddressConfirmation is returned by the counterparty after receiving an Address
// proof-of-control query. The counterparty should echo the address received (updating
// it as necessary) then specify controlled_by_entity as true if it is controlled by
// the receiving party or false and include an error if it is not. This is sufficient
// for simple address confirmation. For other
type AddressConfirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The address that is being confirmed by the counterparty.
	Address *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Specify true if the crypto address is controlled by the counterparty; specifying
	// this as true is sufficient for simple address confirmation. If the counterparty
	// cannot or will not perform the address confirmation they can mark this field as
	// false and include an error code and message. Counterparties that will never do
	// address confirmation should return a gRPC Unimplemented status code to this RPC.
	ControlledByEntity bool `protobuf:"varint,2,opt,name=controlled_by_entity,json=controlledByEntity,proto3" json:"controlled_by_entity,omitempty"`
	// Rejection errors should be specified in the response if the counterparty cannot
	// or will not perform an address confirmation. Generally the error codes that are
	// returned here are UNKNOWN_WALLET_ADDRESS, UNSUPPORTED_NETWORK,
	// UNSUPPORTED_ADDRESS_CONFIRMATION, or CANNOT_CONFIRM_CONTROL_OF_ADDRESS -- but
	// other codes may be used if necessary.
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// If the confirmation type is key/token or on-chain then additional details must
	// be specified for the address confirmation. If the confirmation type is simple,
	// then this field may be left empty.
	//
	// Types that are assignable to ConfirmationDetails:
	//
	//	*AddressConfirmation_KeyToken
	//	*AddressConfirmation_OnChain
	ConfirmationDetails isAddressConfirmation_ConfirmationDetails `protobuf_oneof:"confirmation_details"`
}

func (x *AddressConfirmation) Reset() {
	*x = AddressConfirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressConfirmation) ProtoMessage() {}

func (x *AddressConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressConfirmation.ProtoReflect.Descriptor instead.
func (*AddressConfirmation) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{3}
}

func (x *AddressConfirmation) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AddressConfirmation) GetControlledByEntity() bool {
	if x != nil {
		return x.ControlledByEntity
	}
	return false
}

func (x *AddressConfirmation) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (m *AddressConfirmation) GetConfirmationDetails() isAddressConfirmation_ConfirmationDetails {
	if m != nil {
		return m.ConfirmationDetails
	}
	return nil
}

func (x *AddressConfirmation) GetKeyToken() *KeyTokenConfirm {
	if x, ok := x.GetConfirmationDetails().(*AddressConfirmation_KeyToken); ok {
		return x.KeyToken
	}
	return nil
}

func (x *AddressConfirmation) GetOnChain() *OnChainConfirm {
	if x, ok := x.GetConfirmationDetails().(*AddressConfirmation_OnChain); ok {
		return x.OnChain
	}
	return nil
}

type isAddressConfirmation_ConfirmationDetails interface {
	isAddressConfirmation_ConfirmationDetails()
}

type AddressConfirmation_KeyToken struct {
	KeyToken *KeyTokenConfirm `protobuf:"bytes,8,opt,name=key_token,json=keyToken,proto3,oneof"`
}

type AddressConfirmation_OnChain struct {
	OnChain *OnChainConfirm `protobuf:"bytes,9,opt,name=on_chain,json=onChain,proto3,oneof"`
}

func (*AddressConfirmation_KeyToken) isAddressConfirmation_ConfirmationDetails() {}

func (*AddressConfirmation_OnChain) isAddressConfirmation_ConfirmationDetails() {}

type KeyTokenQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A token encrypted by the public key of the wallet address.
	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// The algorithm used to encrypt the token.
	PublicKeyAlgorithm string `protobuf:"bytes,4,opt,name=public_key_algorithm,json=publicKeyAlgorithm,proto3" json:"public_key_algorithm,omitempty"`
	// The signature of the public key, used to identify the key pair.
	PublicKeySignature string `protobuf:"bytes,12,opt,name=public_key_signature,json=publicKeySignature,proto3" json:"public_key_signature,omitempty"`
}

func (x *KeyTokenQuery) Reset() {
	*x = KeyTokenQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyTokenQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyTokenQuery) ProtoMessage() {}

func (x *KeyTokenQuery) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyTokenQuery.ProtoReflect.Descriptor instead.
func (*KeyTokenQuery) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{4}
}

func (x *KeyTokenQuery) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *KeyTokenQuery) GetPublicKeyAlgorithm() string {
	if x != nil {
		return x.PublicKeyAlgorithm
	}
	return ""
}

func (x *KeyTokenQuery) GetPublicKeySignature() string {
	if x != nil {
		return x.PublicKeySignature
	}
	return ""
}

type KeyTokenConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The decrypted token to confirm to the user that the counterparty has control of
	// the private keys of the crypto address.
	DecryptedToken []byte `protobuf:"bytes,1,opt,name=decrypted_token,json=decryptedToken,proto3" json:"decrypted_token,omitempty"`
}

func (x *KeyTokenConfirm) Reset() {
	*x = KeyTokenConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyTokenConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyTokenConfirm) ProtoMessage() {}

func (x *KeyTokenConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyTokenConfirm.ProtoReflect.Descriptor instead.
func (*KeyTokenConfirm) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{5}
}

func (x *KeyTokenConfirm) GetDecryptedToken() []byte {
	if x != nil {
		return x.DecryptedToken
	}
	return nil
}

type OnChainQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The beneficiary address of the wallet to send the proof of control amount to.
	BeneficiaryAddress string `protobuf:"bytes,1,opt,name=beneficiary_address,json=beneficiaryAddress,proto3" json:"beneficiary_address,omitempty"`
	// Amount of the transaction (usually a small amount) - this is the nonce value.
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// The RFC3339 encoded timestamp of when the transaction must be posted by.
	NotAfter string `protobuf:"bytes,3,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
}

func (x *OnChainQuery) Reset() {
	*x = OnChainQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainQuery) ProtoMessage() {}

func (x *OnChainQuery) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainQuery.ProtoReflect.Descriptor instead.
func (*OnChainQuery) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{6}
}

func (x *OnChainQuery) GetBeneficiaryAddress() string {
	if x != nil {
		return x.BeneficiaryAddress
	}
	return ""
}

func (x *OnChainQuery) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OnChainQuery) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

type OnChainConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The RFC3339 encoded timestamp of when transaction will be visible.
	NotBefore string `protobuf:"bytes,1,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	// The actual amount posted in the transaction for verification.
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// The transaction ID of the confirmation, if available
	Txid string `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
}

func (x *OnChainConfirm) Reset() {
	*x = OnChainConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainConfirm) ProtoMessage() {}

func (x *OnChainConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainConfirm.ProtoReflect.Descriptor instead.
func (*OnChainConfirm) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{7}
}

func (x *OnChainConfirm) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *OnChainConfirm) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OnChainConfirm) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

// SigningKey provides metadata for decoding a PEM encoded PKIX public key for RSA
// encryption and transaction signing. The SigningKey is a lightweight version of the
// Certificate information stored in the Directory Service.
type SigningKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// x.509 metadata information for ease of reference without parsing the key.
	Version            int64  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Signature          []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureAlgorithm string `protobuf:"bytes,3,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	PublicKeyAlgorithm string `protobuf:"bytes,4,opt,name=public_key_algorithm,json=publicKeyAlgorithm,proto3" json:"public_key_algorithm,omitempty"`
	// Validity information
	NotBefore string `protobuf:"bytes,8,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter  string `protobuf:"bytes,9,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Revoked   bool   `protobuf:"varint,10,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// The serialized public key to PKIX, ASN.1 DER form.
	Data []byte `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SigningKey) Reset() {
	*x = SigningKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKey) ProtoMessage() {}

func (x *SigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKey.ProtoReflect.Descriptor instead.
func (*SigningKey) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{8}
}

func (x *SigningKey) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SigningKey) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SigningKey) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *SigningKey) GetPublicKeyAlgorithm() string {
	if x != nil {
		return x.PublicKeyAlgorithm
	}
	return ""
}

func (x *SigningKey) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *SigningKey) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *SigningKey) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *SigningKey) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The number of failed health checks that proceeded the current check.
	Attempts uint32 `protobuf:"varint,1,opt,name=attempts,proto3" json:"attempts,omitempty"`
	// The timestamp of the last health check, successful or otherwise.
	LastCheckedAt string `protobuf:"bytes,2,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"`
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheck) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *HealthCheck) GetLastCheckedAt() string {
	if x != nil {
		return x.LastCheckedAt
	}
	return ""
}

type ServiceState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Current service status as defined by the recieving system. The system is obliged
	// to respond with the closest matching status in a best-effort fashion. Alerts will
	// be triggered on service status changes if the system does not respond and the
	// previous system state was not unknown.
	Status ServiceState_Status `protobuf:"varint,1,opt,name=status,proto3,enum=trisa.api.v1beta1.ServiceState_Status" json:"status,omitempty"`
	// Suggest to the directory service when to check the health status again.
	NotBefore string `protobuf:"bytes,2,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter  string `protobuf:"bytes,3,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
}

func (x *ServiceState) Reset() {
	*x = ServiceState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trisa_api_v1beta1_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceState) ProtoMessage() {}

func (x *ServiceState) ProtoReflect() protoreflect.Message {
	mi := &file_trisa_api_v1beta1_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceState.ProtoReflect.Descriptor instead.
func (*ServiceState) Descriptor() ([]byte, []int) {
	return file_trisa_api_v1beta1_api_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceState) GetStatus() ServiceState_Status {
	if x != nil {
		return x.Status
	}
	return ServiceState_UNKNOWN
}

func (x *ServiceState) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *ServiceState) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

var File_trisa_api_v1beta1_api_proto protoreflect.FileDescriptor

var file_trisa_api_v1beta1_api_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x74,
	0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x74, 0x72, 0x69,
	0x73, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x03, 0x0a, 0x0e,
	0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x31, 0x0a, 0x14, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6d, 0x61, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x6d, 0x61, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x6d, 0x61, 0x63, 0x5f, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x68, 0x6d, 0x61,
	0x63, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x6d, 0x61, 0x63, 0x5f,
	0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x68, 0x6d, 0x61, 0x63, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x2e,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x6c, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20,
	0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0xad, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x41, 0x6e, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x36, 0x0a,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x22,
	0xdb, 0x02, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x47, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x23, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x3f, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x72, 0x69, 0x73,
	0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4b, 0x65,
	0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x08, 0x6b,
	0x65, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3c, 0x0a, 0x08, 0x6f, 0x6e, 0x5f, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x72, 0x69, 0x73,
	0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4f, 0x6e,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x6e,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x16, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xc8, 0x02,
	0x0a, 0x13, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2e, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74,
	0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x41, 0x0a,
	0x09, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x3e, 0x0a, 0x08, 0x6f, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x42, 0x16, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x0d, 0x4b, 0x65, 0x79,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x30, 0x0a, 0x14, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x61,
	0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x12, 0x30, 0x0a, 0x14, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x3a, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0e, 0x64, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x74, 0x0a, 0x0c, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x2f, 0x0a, 0x13, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x63, 0x69, 0x61, 0x72, 0x79, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x62,
	0x65, 0x6e, 0x65, 0x66, 0x69, 0x63, 0x69, 0x61, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x74,
	0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f,
	0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0e, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x5f,
	0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f,
	0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x78, 0x69, 0x64, 0x22, 0x91, 0x02, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b,
	0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x30, 0x0a, 0x14, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69,
	0x74, 0x68, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x1d, 0x0a,
	0x0a, 0x6e, 0x6f, 0x74, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x76,
	0x6f, 0x6b, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x76, 0x6f,
	0x6b, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x73,
	0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x74, 0x22, 0xe7, 0x01, 0x0a, 0x0c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x74, 0x72,
	0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x6f, 0x74, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f,
	0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x6f, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x55,
	0x4e, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x41,
	0x4e, 0x47, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e,
	0x45, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e,
	0x43, 0x45, 0x10, 0x05, 0x2a, 0x7d, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x45, 0x50, 0x41, 0x49, 0x52, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x43, 0x45,
	0x50, 0x54, 0x45, 0x44, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x44, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45,
	0x44, 0x10, 0x07, 0x2a, 0x46, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49, 0x4d, 0x50, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x4b, 0x45, 0x59, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x4f, 0x4e, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x10, 0x03, 0x32, 0xe7, 0x02, 0x0a, 0x0c,
	0x54, 0x52, 0x49, 0x53, 0x41, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x52, 0x0a, 0x08,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x1a, 0x21, 0x2e, 0x74, 0x72,
	0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x22, 0x00,
	0x12, 0x5c, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x21, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x45, 0x6e, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x1a, 0x21, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x56,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x26, 0x2e, 0x74,
	0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0b, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x67, 0x4b, 0x65, 0x79, 0x1a, 0x1d, 0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67,
	0x4b, 0x65, 0x79, 0x22, 0x00, 0x32, 0x5a, 0x0a, 0x0b, 0x54, 0x52, 0x49, 0x53, 0x41, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x12, 0x4b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e,
	0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x1a, 0x1f,
	0x2e, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x00, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x72, 0x69, 0x73, 0x61, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x69, 0x73,
	0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x72, 0x69, 0x73, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_trisa_api_v1beta1_api_proto_rawDescOnce sync.Once
	file_trisa_api_v1beta1_api_proto_rawDescData = file_trisa_api_v1beta1_api_proto_rawDesc
)

func file_trisa_api_v1beta1_api_proto_rawDescGZIP() []byte {
	file_trisa_api_v1beta1_api_proto_rawDescOnce.Do(func() {
		file_trisa_api_v1beta1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_trisa_api_v1beta1_api_proto_rawDescData)
	})
	return file_trisa_api_v1beta1_api_proto_rawDescData
}

var file_trisa_api_v1beta1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_trisa_api_v1beta1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_trisa_api_v1beta1_api_proto_goTypes = []interface{}{
	(TransferState)(0),          // 0: trisa.api.v1beta1.TransferState
	(ConfirmationType)(0),       // 1: trisa.api.v1beta1.ConfirmationType
	(ServiceState_Status)(0),    // 2: trisa.api.v1beta1.ServiceState.Status
	(*SecureEnvelope)(nil),      // 3: trisa.api.v1beta1.SecureEnvelope
	(*Payload)(nil),             // 4: trisa.api.v1beta1.Payload
	(*Address)(nil),             // 5: trisa.api.v1beta1.Address
	(*AddressConfirmation)(nil), // 6: trisa.api.v1beta1.AddressConfirmation
	(*KeyTokenQuery)(nil),       // 7: trisa.api.v1beta1.KeyTokenQuery
	(*KeyTokenConfirm)(nil),     // 8: trisa.api.v1beta1.KeyTokenConfirm
	(*OnChainQuery)(nil),        // 9: trisa.api.v1beta1.OnChainQuery
	(*OnChainConfirm)(nil),      // 10: trisa.api.v1beta1.OnChainConfirm
	(*SigningKey)(nil),          // 11: trisa.api.v1beta1.SigningKey
	(*HealthCheck)(nil),         // 12: trisa.api.v1beta1.HealthCheck
	(*ServiceState)(nil),        // 13: trisa.api.v1beta1.ServiceState
	(*Error)(nil),               // 14: trisa.api.v1beta1.Error
	(*anypb.Any)(nil),           // 15: google.protobuf.Any
}
var file_trisa_api_v1beta1_api_proto_depIdxs = []int32{
	14, // 0: trisa.api.v1beta1.SecureEnvelope.error:type_name -> trisa.api.v1beta1.Error
	0,  // 1: trisa.api.v1beta1.SecureEnvelope.transfer_state:type_name -> trisa.api.v1beta1.TransferState
	15, // 2: trisa.api.v1beta1.Payload.identity:type_name -> google.protobuf.Any
	15, // 3: trisa.api.v1beta1.Payload.transaction:type_name -> google.protobuf.Any
	1,  // 4: trisa.api.v1beta1.Address.confirmation:type_name -> trisa.api.v1beta1.ConfirmationType
	7,  // 5: trisa.api.v1beta1.Address.key_token:type_name -> trisa.api.v1beta1.KeyTokenQuery
	9,  // 6: trisa.api.v1beta1.Address.on_chain:type_name -> trisa.api.v1beta1.OnChainQuery
	5,  // 7: trisa.api.v1beta1.AddressConfirmation.address:type_name -> trisa.api.v1beta1.Address
	14, // 8: trisa.api.v1beta1.AddressConfirmation.error:type_name -> trisa.api.v1beta1.Error
	8,  // 9: trisa.api.v1beta1.AddressConfirmation.key_token:type_name -> trisa.api.v1beta1.KeyTokenConfirm
	10, // 10: trisa.api.v1beta1.AddressConfirmation.on_chain:type_name -> trisa.api.v1beta1.OnChainConfirm
	2,  // 11: trisa.api.v1beta1.ServiceState.status:type_name -> trisa.api.v1beta1.ServiceState.Status
	3,  // 12: trisa.api.v1beta1.TRISANetwork.Transfer:input_type -> trisa.api.v1beta1.SecureEnvelope
	3,  // 13: trisa.api.v1beta1.TRISANetwork.TransferStream:input_type -> trisa.api.v1beta1.SecureEnvelope
	5,  // 14: trisa.api.v1beta1.TRISANetwork.ConfirmAddress:input_type -> trisa.api.v1beta1.Address
	11, // 15: trisa.api.v1beta1.TRISANetwork.KeyExchange:input_type -> trisa.api.v1beta1.SigningKey
	12, // 16: trisa.api.v1beta1.TRISAHealth.Status:input_type -> trisa.api.v1beta1.HealthCheck
	3,  // 17: trisa.api.v1beta1.TRISANetwork.Transfer:output_type -> trisa.api.v1beta1.SecureEnvelope
	3,  // 18: trisa.api.v1beta1.TRISANetwork.TransferStream:output_type -> trisa.api.v1beta1.SecureEnvelope
	6,  // 19: trisa.api.v1beta1.TRISANetwork.ConfirmAddress:output_type -> trisa.api.v1beta1.AddressConfirmation
	11, // 20: trisa.api.v1beta1.TRISANetwork.KeyExchange:output_type -> trisa.api.v1beta1.SigningKey
	13, // 21: trisa.api.v1beta1.TRISAHealth.Status:output_type -> trisa.api.v1beta1.ServiceState
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_trisa_api_v1beta1_api_proto_init() }
func file_trisa_api_v1beta1_api_proto_init() {
	if File_trisa_api_v1beta1_api_proto != nil {
		return
	}
	file_trisa_api_v1beta1_errors_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_trisa_api_v1beta1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecureEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressConfirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyTokenQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyTokenConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trisa_api_v1beta1_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_trisa_api_v1beta1_api_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Address_KeyToken)(nil),
		(*Address_OnChain)(nil),
	}
	file_trisa_api_v1beta1_api_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*AddressConfirmation_KeyToken)(nil),
		(*AddressConfirmation_OnChain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trisa_api_v1beta1_api_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_trisa_api_v1beta1_api_proto_goTypes,
		DependencyIndexes: file_trisa_api_v1beta1_api_proto_depIdxs,
		EnumInfos:         file_trisa_api_v1beta1_api_proto_enumTypes,
		MessageInfos:      file_trisa_api_v1beta1_api_proto_msgTypes,
	}.Build()
	File_trisa_api_v1beta1_api_proto = out.File
	file_trisa_api_v1beta1_api_proto_rawDesc = nil
	file_trisa_api_v1beta1_api_proto_goTypes = nil
	file_trisa_api_v1beta1_api_proto_depIdxs = nil
}
