baseURL = "https://trisa.dev/"
theme = "hugo-theme-relearn"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false

[params]

    # Source Code repository section
    description = "TRISA Documentation"
    github_repository = "https://github.com/trisacrypto/trisa"
    version = "v1beta1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/trisacrypto/trisa"

    # Analytic section
    googleAnalytics = "G-F9T1H8EJJS"      # Your Google Analytics tracking id

    # When using multilingual website, disable the switch language button.
    disableLanguageSwitchingButton = false

    # Theme settings section
    # Theme color
    themeVariant = "blue"
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Theme settings section
    dateformat = "January 2, 2006" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = []

    disableInlineCopyToClipBoard = true

    disableShortcutsTitle = true

    favicon = "favicon.png"

    additionalContentLanguage = ['en']

    disableAssetsBusting = true

[languages]
  [languages.en]
    title = "TRISA Documentation"
    weight = 1
    languageName = "English"

  [languages.en.params]
    landingPageName = "<i class='fas fa-home'></i> Home"

  [[languages.en.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Version v1beta1"
    identifier = "ds"
    url = "https://github.com/trisacrypto/trisa"
    weight = 10

  [[languages.en.menu.shortcuts]]
    name = "<i class='fas fa-book'></i> TRISA API Documentation"
    identifier = "trisadocs"
    url = "https://pkg.go.dev/github.com/trisacrypto/trisa/pkg"
    weight = 11

  [languages.de]
    title = "TRISA Dokumentation"
    weight = 2
    languageName = "Deutsch"

  [languages.de.params]
    landingPageName = "<i class='fas fa-home'></i> Startseite"

  [[languages.de.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Version v1beta1"
    identifier = "ds"
    url = "https://github.com/trisacrypto/trisa"
    weight = 12

  [[languages.de.menu.shortcuts]]
    name = "<i class='fas fa-book'></i> TRISA API Documentation"
    identifier = "trisadocs"
    url = "https://pkg.go.dev/github.com/trisacrypto/trisa/pkg"
    weight = 13

  [languages.fr]
    title = "Documentation de TRISA"
    weight = 3
    languageName = "Français"

  [languages.fr.params]
    landingPageName = "<i class='fas fa-home'></i> Accueil"

  [[languages.fr.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Version v1beta1"
    identifier = "ds"
    url = "https://github.com/trisacrypto/trisa"
    weight = 14

   [[languages.fr.menu.shortcuts]]
    name = "<i class='fas fa-book'></i> TRISA API Documentation"
    identifier = "trisadocs"
    url = "https://pkg.go.dev/github.com/trisacrypto/trisa/pkg"
    weight = 15

  [languages.zh]
    title = "TRISA 文档"
    weight = 4
    languageName = "中文"

  [languages.zh.params]
    landingPageName = "<i class='fas fa-home'></i> 主页"

  [[languages.zh.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Version v1beta1"
    identifier = "ds"
    url = "https://github.com/trisacrypto/trisa"
    weight = 16

  [[languages.zh.menu.shortcuts]]
    name = "<i class='fas fa-book'></i> TRISA API Documentation"
    identifier = "trisadocs"
    url = "https://pkg.go.dev/github.com/trisacrypto/trisa/pkg"
    weight = 17

  [languages.ja]
    title = "TRISAのドキュメント"
    weight = 5
    languageName = "日本語"

  [languages.ja.params]
    landingPageName = "<i class='fas fa-home'></i> ホームページ"

  [[languages.ja.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Version v1beta1"
    identifier = "ds"
    url = "https://github.com/trisacrypto/trisa"
    weight = 18

  [[languages.ja.menu.shortcuts]]
    name = "<i class='fas fa-book'></i> TRISA API Documentation"
    identifier = "trisadocs"
    url = "https://pkg.go.dev/github.com/trisacrypto/trisa/pkg"
    weight = 19

[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = false

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'nord'
    tabWidth = 4