apiVersion: skaffold/v1
kind: Config
metadata:
  name: gohugo
build:
  artifacts:
  - image: trisacrypto/tooling
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
        GOHUGO_RELEASE: 0.61.0
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:gohugo-dev'
  local:
    push: false
profiles:
- name: travis-pr
  activation:
    - env: TRAVIS_EVENT_TYPE=pull_request
  build:
    tagPolicy:
      envTemplate:
        template: '{{.IMAGE_NAME}}:gohugo-pr-{{.TRAVIS_PULL_REQUEST}}'
    local:
      push: true
- name: travis-push
  activation:
    - env: TRAVIS_EVENT_TYPE=push
    - env: TRAVIS_EVENT_TYPE=cron
  build:
    tagPolicy:
      envTemplate:
        template: '{{.IMAGE_NAME}}:gohugo'
    local:
      push: true